project_id = "twbqokjjdopxcgiiuluz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54324

[edge_functions]
enabled = true
port = 54325

[functions.create-payment-session]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.send-reservation-email]
verify_jwt = false

[functions.submit-form-data]
verify_jwt = false

[functions.send-form-notification-email]
verify_jwt = false

[functions.send-admin-welcome-email]
verify_jwt = false

[functions.send-payment-failure-email]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = true

[functions.send-job-application-email]
verify_jwt = false